// SVG is XML, so the metadata is right there in the markup: <metadata> blocks
// holding RDF and C2PA, generator comments, and the private namespaces that
// editors scatter through the tree.

import type { Finding } from "../types";
import { finding, mergeFindings } from "./common";
import { processText, DEFAULT_TEXT_OPTIONS, type TextOptions } from "../unicode";

/** Namespace prefixes that only exist to serve one editor. */
const EDITOR_PREFIXES = ["inkscape", "sodipodi", "adobe", "illustrator", "graph", "i", "x"];

export function stripSvg(source: string, textOptions: TextOptions | null) {
  const findings: Finding[] = [];
  let svg = source;

  // <metadata> — the usual home for RDF, Dublin Core and C2PA manifests.
  const metadataBlocks = svg.match(/<metadata[\s\S]*?<\/metadata>/gi);
  if (metadataBlocks) {
    const joined = metadataBlocks.join("");
    const isC2pa = /c2pa|contentauth/i.test(joined);
    findings.push(
      finding(
        "svg:metadata",
        isC2pa ? "C2PA content credentials" : "Metadata block",
        isC2pa
          ? "A signed provenance manifest embedded in the document."
          : "RDF / Dublin Core records naming the author and tool.",
        "high",
        metadataBlocks.length,
      ),
    );
    svg = svg.replace(/<metadata[\s\S]*?<\/metadata>/gi, "");
  }

  // Generator comments: <!-- Generator: Adobe Illustrator ... -->
  const comments = svg.match(/<!--[\s\S]*?-->/g);
  if (comments) {
    const generator = comments.find((c) => /generator|created with|exported/i.test(c));
    findings.push(
      finding(
        "svg:comments",
        generator ? "Generator comment" : "XML comments",
        generator
          ? `Names the tool that produced the file: ${generator.replace(/<!--|-->/g, "").trim().slice(0, 100)}`
          : "Comments left in the markup.",
        generator ? "medium" : "low",
        comments.length,
      ),
    );
    svg = svg.replace(/<!--[\s\S]*?-->/g, "");
  }

  // Editor-private attributes and their namespace declarations.
  let editorAttrs = 0;
  for (const prefix of EDITOR_PREFIXES) {
    const attr = new RegExp(`\\s${prefix}:[\\w-]+\\s*=\\s*("[^"]*"|'[^']*')`, "gi");
    const nsDecl = new RegExp(`\\sxmlns:${prefix}\\s*=\\s*("[^"]*"|'[^']*')`, "gi");
    editorAttrs += (svg.match(attr) ?? []).length;
    svg = svg.replace(attr, "").replace(nsDecl, "");
  }
  if (editorAttrs > 0) {
    findings.push(
      finding(
        "svg:editor-attrs",
        "Editor-private attributes",
        "Inkscape / Illustrator working state: layer names, window positions, document ids.",
        "medium",
        editorAttrs,
      ),
    );
  }

  // <desc> is used for accessibility, so it stays — but a bare tool name in it
  // is provenance, not description.
  svg = svg.replace(/<desc>\s*(Created with|Generated by|Made with)[^<]*<\/desc>/gi, () => {
    findings.push(
      finding("svg:desc", "Generator description", "A <desc> element naming the authoring tool.", "medium"),
    );
    return "";
  });

  if (textOptions) {
    const result = processText(svg, textOptions);
    if (result.totalMarks > 0) {
      findings.push(...result.findings);
      svg = result.text;
    }
  }

  // Collapse the blank lines left behind.
  svg = svg.replace(/\n\s*\n\s*\n/g, "\n\n").trim() + "\n";

  return { text: svg, findings: mergeFindings(findings), lossless: true };
}

export const SVG_DEFAULT_TEXT: TextOptions = { ...DEFAULT_TEXT_OPTIONS, typography: false };
